### ISSUE TITLE
FAUST installation problem

### ISSUE THREAD

**Issue by algebio** [RGLab/FAUST#1]
Hi 

I'm trying to install FAUST but I'm having a problem to install scamp (see https://github.com/RGLab/scamp/issues/3 
)

I have also tried to install it from source following instructions from 

https://support.rstudio.com/hc/en-us/articles/200486088-Using-Rcpp-with-RStudio

but I get this error: 

install.packages('C:/Users/njo47/R/win-library/3.6/scamp', type="source")
Installing package into ‘C:/Users/njo47/R/win-library/3.6’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘C:/Users/njo47/R/win-library/3.6/scamp’ is not available (for R version 3.6.0)

Any ideas of where is the problem and how to install FAUST?

Thanks
Juan

**Comment by evangreene** [comment]
Hi, 

Please see my response to [RGLab/scamp#3](https://github.com/RGLab/scamp/issues/3). I believe it resolves the issue, so I will close this for the time being. However, if you encounter any issues using faust on Windows, please let me know in another issue.

Thanks,
Evan

**Comment by algebio** [comment]
Solved by author in https://github.com/RGLab/scamp/issues/3
