### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by zonglunli7515** [RGLab/FAUST#13]
Hi,

I have seemingly managed to install scamp. However, after running the suggested lines  

tryCatch(installed.packages()["knitr","Version"],
     error = function(e){
            install.packages("knitr")
         })	
tryCatch(installed.packages()["rmarkdown","Version"],
     error = function(e){
            install.packages("rmarkdown")
         })
tryCatch(installed.packages()["ggdendro","Version"],
     error = function(e){
            install.packages("ggdendro")
         })
tryCatch(installed.packages()["remotes","Version"],
	     error = function(e){
            install.packages("remotes")
         })	
remotes::install_github("RGLab/FAUST", force = TRUE, build_vignettes = TRUE)

**I came across some suspicious/error messages** 

E  creating vignettes (2m 22.4s)
   --- re-building ‘faustIntro.Rmd’ using rmarkdown
   Quitting from lines 70-83 (faustIntro.Rmd) 
   Error: processing vignette 'faustIntro.Rmd' failed with diagnostics:
   there is no package called 'flowWorkspaceData'
   --- failed re-building ‘faustIntro.Rmd’
   
   SUMMARY: processing the following file failed:
     ‘faustIntro.Rmd’
   
   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'faust' from GitHub:
  System command 'R' failed, exit status: 1, stderr empty

Thanks in advance for your help.

Allen

**Comment by gfinak** [comment]
```
Error: processing vignette 'faustIntro.Rmd' failed with diagnostics:
there is no package called 'flowWorkspaceData'
```
You need to install that package to build the vignettes.

**Comment by zonglunli7515** [comment]
> ```
> Error: processing vignette 'faustIntro.Rmd' failed with diagnostics:
> there is no package called 'flowWorkspaceData'
> ```
> 
> You need to install that package to build the vignettes.

Many thanks.

**Comment by zonglunli7515** [comment]
> ```
> Error: processing vignette 'faustIntro.Rmd' failed with diagnostics:
> there is no package called 'flowWorkspaceData'
> ```
> 
> You need to install that package to build the vignettes.

Hi,

Thanks again for your speedy help. I'm very new to R and mass cytometry data analysis.
Btw, do you know how to import my own dataset(s) of fcs format? It seems to me that the example data are contained in package flowWorkspaceData:

gsPath <- system.file("extdata","gs_bcell_auto", package = "flowWorkspaceData")
gs <- load_gs(gsPath)

Best,

Allen

**Comment by gfinak** [comment]
Sure.
You need to leverage the `cytoverse` packages to create a `GatingSet` object containing your compensated, transformed and pre-gated data.
If you try to do population discovery on raw data you'll get nonsense results.. garbage in garbage out still applies.
https://cytoverse.org/
Has more details... see the various package Vignettes on Bioconductor to get started.

**Comment by zonglunli7515** [comment]
> Sure.
> You need to leverage the `cytoverse` packages to create a `GatingSet` object containing your compensated, transformed and pre-gated data.
> If you try to do population discovery on raw data you'll get nonsense results.. garbage in garbage out still applies.
> https://cytoverse.org/
> Has more details... see the various package Vignettes on Bioconductor to get started.

Many thanks!
It still sounds intricate but I will digest it!

Best,

Allen

**Comment by evangreene** [comment]
Closing this issue since it appears the installation difficulties have been resolved. Please open another issue if further installation difficulties are encountered.
