### ISSUE TITLE
"Live" not found

### ISSUE THREAD

**Issue by zonglunli7515** [RGLab/FAUST#14]
Hi,

First of all, I have very limited knowledge of gating...
In the FAUST package document, at step three, "Live" is assigned to startingNode. But what if the gating strategy of my dataset is not provided? I created a gatingSet for my data but I don't know how to get around this manual assignment. It turned out that the gatingSet object of the work example possesses more classes than my gatingSet object. The instruction said openCyto can be used to gate live cells so I browsed the webpage 

https://bioconductor.org/packages/devel/bioc/vignettes/openCyto/inst/doc/HowToAutoGating.html

However, it seems that I still have to reference some variables such as "Live" to indicate the root population that my data don't have... I'm stuck...

Thanks in advance for your help.

Allen

**Comment by gfinak** [comment]
Of you have no gating tree associates with your data, start with "root". But it's strongly recommended to pregate your data to remove debris, select singlets, and maybe even lymphocytes depending on your panel. In fact, that's the approach described in the paper. Clean data should be input to FAUST.

**Comment by zonglunli7515** [comment]
> Of you have no gating tree associates with your data, start with "root". But it's strongly recommended to pregate your data to remove debris, select singlets, and maybe even lymphocytes depending on your panel. In fact, that's the approach described in the paper. Clean data should be input to FAUST.

Many thanks. I really appreciate your speedy help. Step nine seems to be running now and I'm cracking the last step.
