### ISSUE TITLE
Default transformation in FAUST

### ISSUE THREAD

**Issue by onecarbon** [RGLab/FAUST#17]
Hi--

I'm analyzing a dataset with FAUST imported from FlowJo with `CytoML::flowjo_to_gatingset()`. I'm having trouble finding exactly what/where the transformation is that is applied to the raw data in the FAUST or CytoML documentation. Could you clarify this? Thanks!

**Comment by gfinak** [comment]
FAUST doesn't transform anything.
There is no default transformation. The only transform applied is what is
defined in the flowJo workspace. This question would be better suited to
RGLab/flowWorkspace

**Comment by onecarbon** [comment]
Ok thanks. I will look there to see if/where the transformation is applied.
